<script setup lang="ts">
import { computed } from 'vue'
import {
  MATURITY_LABELS,
  MATURITY_VALUES,
  OBJECTIVE_ENV_LABELS,
  OBJECTIVE_ENV_VALUES,
  STATUS_LABELS,
  STATUS_VALUES,
  type ObjectiveEnvValue,
  type ProjectFilters,
  type ProjectMaturity,
  type ProjectStatus,
} from '~/types/project'

interface Props {
  modelValue: ProjectFilters
}

const props = defineProps<Props>()

const emit = defineEmits<{
  'update:modelValue': [filters: ProjectFilters]
}>()

const status = computed<ProjectStatus | ''>({
  get: () => (props.modelValue.status ?? '') as ProjectStatus | '',
  set: (v) => emit('update:modelValue', { ...props.modelValue, status: v || undefined }),
})

const maturity = computed<ProjectMaturity | ''>({
  get: () => (props.modelValue.maturity ?? '') as ProjectMaturity | '',
  set: (v) => emit('update:modelValue', { ...props.modelValue, maturity: v || undefined }),
})

const objectiveEnv = computed<ObjectiveEnvValue | ''>({
  get: () =>
    (props.modelValue.objective_env ?? '') as ObjectiveEnvValue | '',
  set: (v) =>
    emit('update:modelValue', {
      ...props.modelValue,
      objective_env: v || undefined,
    }),
})

const autoGenerated = computed<boolean | undefined>({
  get: () => props.modelValue.auto_generated,
  set: (v) =>
    emit('update:modelValue', { ...props.modelValue, auto_generated: v }),
})

function reset() {
  emit('update:modelValue', { page: 1, limit: props.modelValue.limit ?? 25 })
}
</script>

<template>
  <div
    role="search"
    class="rounded-lg border border-gray-200 dark:border-dark-border bg-white dark:bg-dark-card p-4 space-y-4"
  >
    <h2 class="text-sm font-semibold text-surface-text dark:text-surface-dark-text">
      Filtres
    </h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
      <div>
        <label
          for="filter-status"
          class="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1"
        >
          Statut
        </label>
        <select
          id="filter-status"
          v-model="status"
          class="w-full px-3 py-2 text-sm rounded-md border border-gray-300 dark:border-dark-border bg-white dark:bg-dark-input text-surface-text dark:text-surface-dark-text focus:outline-none focus:ring-2 focus:ring-brand-green"
        >
          <option value="">Tous</option>
          <option v-for="s in STATUS_VALUES" :key="s" :value="s">
            {{ STATUS_LABELS[s] }}
          </option>
        </select>
      </div>
      <div>
        <label
          for="filter-maturity"
          class="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1"
        >
          Maturité
        </label>
        <select
          id="filter-maturity"
          v-model="maturity"
          class="w-full px-3 py-2 text-sm rounded-md border border-gray-300 dark:border-dark-border bg-white dark:bg-dark-input text-surface-text dark:text-surface-dark-text focus:outline-none focus:ring-2 focus:ring-brand-green"
        >
          <option value="">Toutes</option>
          <option v-for="m in MATURITY_VALUES" :key="m" :value="m">
            {{ MATURITY_LABELS[m] }}
          </option>
        </select>
      </div>
      <div>
        <label
          for="filter-objective"
          class="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1"
        >
          Objectif
        </label>
        <select
          id="filter-objective"
          v-model="objectiveEnv"
          class="w-full px-3 py-2 text-sm rounded-md border border-gray-300 dark:border-dark-border bg-white dark:bg-dark-input text-surface-text dark:text-surface-dark-text focus:outline-none focus:ring-2 focus:ring-brand-green"
        >
          <option value="">Tous</option>
          <option v-for="o in OBJECTIVE_ENV_VALUES" :key="o" :value="o">
            {{ OBJECTIVE_ENV_LABELS[o] }}
          </option>
        </select>
      </div>
      <div>
        <label
          for="filter-auto-generated"
          class="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1"
        >
          Origine
        </label>
        <select
          id="filter-auto-generated"
          :value="autoGenerated === undefined ? '' : autoGenerated ? 'true' : 'false'"
          class="w-full px-3 py-2 text-sm rounded-md border border-gray-300 dark:border-dark-border bg-white dark:bg-dark-input text-surface-text dark:text-surface-dark-text focus:outline-none focus:ring-2 focus:ring-brand-green"
          @change="(e) => {
            const target = e.target as HTMLSelectElement
            const v = target.value
            autoGenerated = v === '' ? undefined : v === 'true'
          }"
        >
          <option value="">Tous</option>
          <option value="false">Manuels</option>
          <option value="true">Auto-générés</option>
        </select>
      </div>
    </div>
    <div class="flex justify-end">
      <button
        type="button"
        class="text-sm text-gray-500 dark:text-gray-400 hover:text-brand-green dark:hover:text-emerald-400"
        @click="reset"
      >
        Réinitialiser
      </button>
    </div>
  </div>
</template>
